version: "3.3"

services:
  chatdemo_builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    container_name: "chatdemo_builder"
    volumes:
      - ".:/home/builder/kotlinMpChatDemo"

  chatdemo:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        PORT: "9020"
        PATH: "/"
    container_name: "chatdemo"
    restart: unless-stopped
    volumes:
      - ".:/home/runner/kotlinMpChatDemo"
    networks:
      - default
    expose:
      - 9020
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=default"
      - "traefik.port=9020"
      - "traefik.http.routers.chatdemo.rule=Host(`chat.zieger.dev`)"
      - "traefik.http.routers.chatdemo.entrypoints=websecure"
      - "traefik.http.routers.chatdemo.tls.certresolver=myresolver"
      - "traefik.http.routers.chatdemo.middlewares=compression, ratelimit"

networks:
  default:
    external:
      name: web
