@startuml
'https://plantuml.com/component-diagram

left to right direction
'!theme cyborg-outline
hide empty members

skinparam defaultFontColor #fff
skinparam titleFontColor #fff
skinparam arrowColor #Fff
skinparam packageBackgroundColor #222
skinparam packageFontColor #f0f
skinparam packageBorderColor #0BF
skinparam rectangleBackgroundColor #011111
skinparam rectangleFontColor #fff
skinparam rectangleBorderColor #0BF
skinparam frameBackgroundColor #011111
skinparam nodeBackgroundColor #111
skinparam nodeFontColor #fff
skinparam nodeBorderColor #0BF
skinparam interfaceBackgroundColor #111
skinparam interfaceFontColor #FFF
skinparam interfaceBorderColor #0F0
skinparam componentStyle rectangle
skinparam RoundCorner<<noRoundCorners>> 0
hide package <<noRoundCorners>> stereotype
hide rectangle <<noRoundCorners>> stereotype
skinparam RoundCorner 25

left to right direction

rectangle {
package "common" as common.common <<noRoundCorners>> {
    component Chat <<noRoundCorners>>
    component ChatClient <<noRoundCorners>>
    [Chat] -> [ChatClient]
}

package desktop <<noRoundCorners>> {
    component DesktopMain <<noRoundCorners>>
    [DesktopMain] -[#yellow]-> [Chat]
}

package android <<noRoundCorners>> {
    component MainActivity <<noRoundCorners>>
    [MainActivity] -[#yellow]-> [Chat]
}

package web <<noRoundCorners>> {
    component WebMain <<noRoundCorners>>
    [WebMain] -[#yellow]-> [Chat]
}

interface User

User .[#green].> android : uses
User .[#green].> desktop : uses

cloud internet {
  [ChatClient] <.[#royalblue].> WebSocket : connect
  User .[#green].> WebSite : requests
}


package "server" <<noRoundCorners>> {
    component Server <<noRoundCorners>>
  WebSocket <.[#violet].> [Server] : provide
  WebSite <.[#violet].> [Server] : serve
  [Server] -[#red]-> [WebMain]
  [ChatBot] <- [Server]
  [Server] -> [DbBridge]
  [Server] --> [EmoticonProvider]
}

database "sqLite" {
    node Users
    node Content
    Users <- Content
}

[DbBridge] --> sqLite

'hide common
'hide sqLite
'hide web
'hide android
'hide desktop
'hide internet
'hide server
'hide User
}
@enduml