@startuml
'https://plantuml.com/component-diagram

left to right direction
'!theme cyborg-outline
hide empty members

skinparam defaultFontColor #fff
skinparam titleFontColor #fff
skinparam arrowColor #Fff
skinparam packageBackgroundColor #222
skinparam packageFontColor #f0f
skinparam packageBorderColor #0BF
skinparam rectangleBackgroundColor #011111
skinparam rectangleFontColor #fff
skinparam rectangleBorderColor #0BF
skinparam frameBackgroundColor #011111
skinparam nodeBackgroundColor #111
skinparam nodeFontColor #fff
skinparam nodeBorderColor #0BF
skinparam interfaceBackgroundColor #111
skinparam interfaceFontColor #FFF
skinparam interfaceBorderColor #0F0
skinparam componentStyle rectangle
skinparam RoundCorner<<roundCorners>> 25
hide rectangle <<roundCorners>> stereotype

left to right direction

rectangle "\n<size:40>**Components**￼" <<roundCorners>> {

    interface User

    User .[#green].> android : uses
    User .[#green].> desktop : uses

    together {
        package common {
            component Chat
            component ChatClient
            [Chat] -> [ChatClient]
            [Chat] --> [TextField]
            [Chat] --> [Link]
            [Chat] --> [Table]
        }

        together {
            package server {
                component Server
              [EmoticonProvider] <- [Server]
              [Server] --> [DbBridge]
              [Server] --> [ChatBot]
            }

            database sqLite {
                node Users
                node Content
                Users <- Content
            }

            server -[hidden]- sqLite
        }
    }

    together {
        cloud internet {
          [ChatClient] <.[#royalblue].> WebSocket : connect
          User .[#green].> WebSite : requests
        }
        WebSocket <.[#violet].> [Server] : provide
        WebSite <.[#violet].> [Server] : serve

        package desktop {
            component DesktopMain
            [DesktopMain] -[#yellow]-> [Chat]
        }

        package android {
            component MainActivity
            [MainActivity] -[#yellow]-> [Chat]
        }

        package web {
            component WebMain
            [WebMain] -[#yellow]-> [Chat]
        }
    }
   [Server] -[#red]-> [WebMain]
    
    
    [DbBridge] --> sqLite
    [ChatBot] --> sqLite
    
    'hide common
    'hide sqLite
    'hide web
    'hide android
    'hide desktop
    'hide internet
    'hide server
    'hide User
}
@enduml