@startuml
'https://plantuml.com/activity-diagram-beta

skinparam arrowColor #FB0
skinparam defaultFontColor #fff
skinparam defaultFontSize 20
skinparam defaultFontStyle bold
skinparam activityBackgroundColor #222
skinparam activityBorderColor #0af
skinparam activityDiamondBackgroundColor #222
skinparam activityStartColor #0f8
skinparam activityDiamondBorderColor #0af
skinparam activityEndColor #f00
skinparam partitionBackgroundColor #333
skinparam partitionBorderColor #0af
skinparam partitionBorderThickness 0.5
skinparam partitionFontColor #f0f
skinparam roundCorner<<roundCorner>> 25
skinparam rectangleBackgroundColor #011111
skinparam rectangleBorderColor #0af

rectangle "" <<roundCorner>> {
    start
    :new tag was pushed;
    if (tag matches pattern '""v[0-9]+\.[0-9]+\.[0-9]+""') then (true)
        :start actions;
            split
                split
                    partition Ubuntu {
                        :build Linux jar;
                        :build Linux Deb;
                    }
                split again
                    partition Windows {
                        :build Windows Jar;
                        :build Windows Msi;
                    }
                split again
                    partition Mac {
                        :build Osx Jar;
                        :build Osx Dmi;
                    }
                split again
                    partition Ubuntu {
                        :build Android Apk;
                    }
            end split

            partition Ubuntu {
                :upload artifacts to server;
            }
            partition Ubuntu {
                :update README.md;
            }

            split again
                partition Ubuntu {
                    :server pul;
                    :server rebuild;
                    :server restart;
                }
        end split
    else (false)
        stop
    endif


    stop
}
@enduml
