@startuml
'https://plantuml.com/component-diagram

left to right direction
skinparam legendBackgroundColor #011
skinparam legendBorderColor #999
skinparam legendFontColor #999

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ <color:green>**build.gradle.kts**</color>
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ <color:green>**gradle.properties.kts**</color>
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ <color:green>**settings.gradle.kts**</color>
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**common**
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**desktop**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**server**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**web**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ src
    |_ <color:orange>**jvmMain**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**common**</color>
  |_ src
    |_ commonMain
    |_ jvmMain
    |_ jsMain
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ src
    |_ jvmMain
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ src
    |_ jvmMain
|_ <color:#0099FF>**web**</color>
  |_ src
    |_ jsMain
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>common
  |_ src
    |_ <color:orange>**commonMain**</color>
    |_ <color:orange>**jvmMain**</color>
    |_ <color:orange>**jsMain**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**</color>
  |_ src
    |_ commonMain
    |_ jvmMain
    |_ jsMain
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ src
    |_ <color:orange>**jvmMain**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**</color>
  |_ src
    |_ commonMain
    |_ jvmMain
    |_ jsMain
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ src
    |_ jvmMain
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ src
    |_ <color:orange>**jvmMain**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>**android**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**</color>
  |_ src
    |_ commonMain
    |_ jvmMain
    |_ jsMain
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ src
    |_ jvmMain
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ src
    |_ jvmMain
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ src
    |_ <color:orange>**jsMain**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>**android**</color>
  |_ src
    |_ <color:orange>**jvmMain**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**common**</color>
  |_ src
    |_ commonMain
    |_ jvmMain
    |_ jsMain
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ src
    |_ jvmMain
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ src
    |_ jvmMain
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ src
    |_ jsMain
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ src
    |_ <color:orange>**jvmMain**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>common
  |_ src
    |_ <color:orange>**commonMain**</color>
    |_ <color:orange>**jvmMain**</color>
    |_ <color:orange>**jsMain**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>desktop</color>
  |_ src
    |_ <color:orange>**jvmMain**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>server</color>
  |_ src
    |_ <color:orange>**jvmMain**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>web</color>
  |_ src
    |_ <color:orange>**jsMain**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:green>build.gradle.kts</color>
|_ <color:green>gradle.properties.kts</color>
|_ <color:green>settings.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
        |_ Link.kt
        |_ Table.kt
        |_ <color:yellow>**TextField.kt**</color>
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ Table.kt
          |_ <color:magenta>**TextField.kt**</color>
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ Table.kt
          |_ <color:magenta>**TextField.kt**</color>
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
        |_ Link.kt
        |_ Table.kt
        |_ <color:magenta>**TextField.kt**</color>
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ Table.kt
          |_ <color:yellow>**TextField.kt**</color>
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ Table.kt
          |_ <color:magenta>**TextField.kt**</color>
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
        |_ Link.kt
        |_ Table.kt
        |_ <color:magenta>**TextField.kt**</color>
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ Table.kt
          |_ <color:magenta>**TextField.kt**</color>
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ Table.kt
          |_ <color:yellow>**TextField.kt**</color>
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
        |_ <color:yellow>**Link.kt**</color>
        |_ Table.kt
        |_ TextField.kt
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**Link.kt**</color>
          |_ Table.kt
          |_ TextField.kt
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**Link.kt**</color>
          |_ Table.kt
          |_ TextField.kt
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
        |_ <color:magenta>**Link.kt**</color>
        |_ Table.kt
        |_ TextField.kt
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ <color:yellow>**Link.kt**</color>
          |_ Table.kt
          |_ TextField.kt
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**Link.kt**</color>
          |_ Table.kt
          |_ TextField.kt
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
        |_ <color:magenta>**Link.kt**</color>
        |_ Table.kt
        |_ TextField.kt
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**Link.kt**</color>
          |_ Table.kt
          |_ TextField.kt
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:yellow>**Link.kt**</color>
          |_ Table.kt
          |_ TextField.kt
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
          |_ Link.kt
          |_ <color:yellow>**Table.kt**</color>
        |_ TextField.kt
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ <color:magenta>**Table.kt**</color>
          |_ TextField.kt
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ <color:magenta>**Table.kt**</color>
          |_ TextField.kt
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
          |_ Link.kt
          |_ <color:magenta>**Table.kt**</color>
        |_ TextField.kt
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ <color:yellow>**Table.kt**</color>
          |_ TextField.kt
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ <color:magenta>**Table.kt**</color>
          |_ TextField.kt
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ Chat.kt
          |_ ChatClient.kt
        |_ Constants.kt
          |_ Link.kt
          |_ <color:magenta>**Table.kt**</color>
        |_ TextField.kt
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ <color:magenta>**Table.kt**</color>
          |_ TextField.kt
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ <color:yellow>**Table.kt**</color>
          |_ TextField.kt
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
**Root**
|_ <color:#0099FF>android</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:yellow>**MainActivity.kt**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>desktop</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**DesktopMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>web</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**WebMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
**Root**
|_ <color:#0099FF>android</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**MainActivity.kt**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>desktop</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:yellow>**DesktopMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>web</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**WebMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
**Root**
|_ <color:#0099FF>android</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**MainActivity.kt**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>desktop</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**DesktopMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>web</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:yellow>**WebMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
end legend

newpage
legend
**Root**
|_ <color:#0099FF>android</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:yellow>**MainActivity.kt**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>common</color>
  |_ src
    |_ <color:orange>commonMain</color>
      |_ kotlin
        |_ package
          |_ <color:magenta>**Chat.kts**</color>
          |_ ChatClient.kt
        |_ Constants.kt
        |_ Link.kt
        |_ Table.kt
        |_ TextField.kt
    |_ <color:orange>jsMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ Table.kt
          |_ TextField.kt
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ Link.kt
          |_ Table.kt
          |_ TextField.kt
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>desktop</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:yellow>**DesktopMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>server</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ db
            |_ ChatContents.kt
            |_ Db.kt
            |_ DbMessageBridge.kt
            |_ Users.kt
          |_ ChatBot.kt
          |_ ChatMessagePipe.kt
          |_ Emoticons.kt
          |_ HtmlFactory.kt
          |_ Server.kt
          |_ <color:yellow>**ServerMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:#0099FF>web</color>
  |_ src
    |_ <color:orange>jvmMain</color>
      |_ kotlin
        |_ package
          |_ <color:yellow>**WebMain.kts**</color>
  |_ <color:green>build.gradle.kts</color>
|_ <color:green>build.gradle.kts</color>
|_ <color:green>gradle.properties.kts</color>
|_ <color:green>settings.gradle.kts</color>
end legend


@enduml