@startuml
'https://plantuml.com/component-diagram

left to right direction
skinparam legendBackgroundColor #011
skinparam legendBorderColor #999
skinparam legendFontColor #999
skinparam leDbuild.gradle.kts
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ <color:green>**build.gradle.kts**</color>
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ <color:green>**gradle.properties.kts**</color>
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ <color:green>**settings.gradle.kts**</color>
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**common**
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**desktop**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**server**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**web**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>android</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ <color:#0099FF>**web**</color>
  |_ build.gradle.kts
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

legend
**Root**
|_ <color:#0099FF>**android**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**common**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**desktop**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**server**</color>
  |_ build.gradle.kts
|_ <color:#0099FF>**web**</color>
  |_ <color:green>**build.gradle.kts**</color>
|_ build.gradle.kts
|_ gradle.properties.kts
|_ settings.gradle.kts
end legend

newpage

hide empty members

title "__Multiplatform Chat Components__"


package common {
    package "common" as common.common {
      [Chat] -> [ChatClient]
    }
    package jvm {

    }
    package js {

    }
}

package desktop {
    [DesktopMain] --> [Chat]
}

package android {
    [MainActivity] --> [Chat]
}

package web {
    [WebMain] --> [Chat]
}

interface User

User ...> android : uses
User ...> desktop : uses

cloud internet {
  [ChatClient] <..> WebSocket : connect
  User ...> WebSite : requests
}


package "server" {
  WebSocket <..> [Server] : provide
  WebSite <..> [Server] : serve
  [Server] --> [WebMain]
}

database "sqLite" {
    node Users
    node Content
    Users <- Content
}

[Server] --> sqLite


'hide common
'hide sqLite
'hide web
'hide android
'hide desktop
'hide internet
'hide server
'hide User

@enduml