@startuml
'https://plantuml.com/sequence-diagram

autonumber

=== Client -> Server ==

box "Client" #LightBlue
    actor User
    User -> Button: User pressed "send" button
    Button -> Chat
    Chat -> TextView: read text content
    return new content
    Chat -> ChatClient: send message
    ChatClient -> "**Clients** DefaultWebSocketServerSession" as CDWSS: send message via websocket to server
end box

box "Server" #Yellow
    "**Servers** DefaultWebSocketServerSession" as SDWSS <- Server ++ : for each ""incoming""
    CDWSS -->o SDWSS: web socket send/receive
    SDWSS -> Server : on new ""Frame.Text""
    participant firstStageChannel

    DbMessageBridge -> DbMessageBridge: read all stored messages
    DbMessageBridge -> secondStageChannel: send all red messages

    secondStageChannel <- ChatBot ++ : for each content

    firstStageChannel <- DbMessageBridge ++ : for each message
    Server -> firstStageChannel: send message
    firstStageChannel -> DbMessageBridge : on new message
    DbMessageBridge -> DbMessageBridge: store new message in DB
    DbMessageBridge -> secondStageChannel: send message

    secondStageChannel -> ChatBot: on new content
    ChatBot -> finalStageChannel: send user messages and bot notifications
    finalStageChannel -> finalStageFlow: convert to Shared Flow

    === Server -> Client ==

    SDWSS <- finalStageFlow: collect all messages and send them to the **Servers** DefaultWebSocketServerSession


end box

@enduml