@startuml
'https://plantuml.com/object-diagram

object London

hide Washington
object Washington
object Berlin
object NewYork

map CapitalCity {
 UK *-> London
 USA *--> Washington
 Germany *---> Berlin
}

Washington <-- CapitalCity::USA
'NewYork <-- CapitalCity::USA
@enduml
