name: MpChatDemo CI

on:
  push:
    tags:
      - 'v*.*.*'

#  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2 

      - name: Build with Gradle
        run: ./assembleApk.sh ${{secrets.ANDROID_KEY_PASSWORD}}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Cache artifacts
        uses: actions/cache@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          path: ./MpChatDemoAndroid/MpChatDemo/${{ env.RELEASE_VERSION }}
          key: android-${{ env.RELEASE_VERSION }}

      - name: Prepare Release
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          mkdir -p ./MpChatDemoAndroid/MpChatDemo/${{ env.RELEASE_VERSION }}
          cp ./MpChatAndroidDemo.apk ./MpChatDemoAndroid/MpChatDemo/${{ env.RELEASE_VERSION }}/MpChatDemo-android-${{ env.RELEASE_VERSION }}.apk


  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build with Gradle
        run: ./gradlew packageDeb packageUberJarForCurrentOS

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Cache artifacts
        uses: actions/cache@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          path: ./MpChatDemoLinux/MpChatDemo/${{ env.RELEASE_VERSION }}
          key: linux-${{ env.RELEASE_VERSION }}

      - name: Prepare Release
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          mkdir -p ./MpChatDemoLinux/MpChatDemo/${{ env.RELEASE_VERSION }}
          cp ./desktop/build/compose/jars/*.jar ./MpChatDemoLinux/MpChatDemo/${{ env.RELEASE_VERSION }}/MpChatDemo-linux-jvm-${{ env.RELEASE_VERSION }}.jar
          cp ./desktop/build/compose/binaries/main/deb/*.deb ./MpChatDemoLinux/MpChatDemo/${{ env.RELEASE_VERSION }}/MpChatDemo-linux-native-${{ env.RELEASE_VERSION }}.deb


  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build with Gradle
        run: ./gradlew packageDmg packageUberJarForCurrentOS

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Cache artifacts
        uses: actions/cache@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          path: ./MpChatDemoMac/MpChatDemo/${{ env.RELEASE_VERSION }}
          key: mac-${{ env.RELEASE_VERSION }}

      - name: Prepare Release
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          mkdir -p ./MpChatDemoMac/MpChatDemo/${{ env.RELEASE_VERSION }}
          cp ./desktop/build/compose/jars/*.jar ./MpChatDemoMac/MpChatDemo/${{ env.RELEASE_VERSION }}/MpChatDemo-mac-jvm-${{ env.RELEASE_VERSION }}.jar
          cp ./desktop/build/compose/binaries/main/dmg/*.dmg ./MpChatDemoMac/MpChatDemo/${{ env.RELEASE_VERSION }}/MpChatDemo-mac-native-${{ env.RELEASE_VERSION }}.dmg


  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build with Gradle
        run: .\gradlew.bat packageDmg packageUberJarForCurrentOS

      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: ./MpChatDemoWin/MpChatDemo/${{ steps.get_version.outputs.version }}
          key: win-${{ steps.get_version.outputs.version }}

      - name: Prepare Release
        run: |
          mkdir ./MpChatDemoWin/${{ steps.get_version.outputs.version }}
          copy .\desktop\build\compose\jars\*.jar ./MpChatDemoWin/MpChatDemo/${{ steps.get_version.outputs.version }}/MpChatDemo-windows-jvm-${{ steps.get_version.outputs.version }}.jar
          copy .\desktop\build\compose\binaries\main\msi\*.msi ./MpChatDemoWin/MpChatDemo/${{ steps.get_version.outputs.version }}/MpChatDemo-windows-native-${{ steps.get_version.outputs.version }}.msi


  trigger-webserver:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger WebServer to build new version
        uses: appleboy/ssh-action@master
        with:
          script: cd ./docker/KotlinMpChatDemo && git pull && ./rebuild.sh && ./restart.sh
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
      

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-android, build-linux, build-mac, build-win ]
    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ steps.vars.outputs.tag }}        

      - name: Cache Android artifact
        uses: actions/cache@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          path: ./MpChatDemoAndroid/MpChatDemo/${{ env.RELEASE_VERSION }}
          key: android-${{ env.RELEASE_VERSION }}

      - name: Cache Linux artifacts
        uses: actions/cache@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          path: ./MpChatDemoLinux/MpChatDemo/${{ env.RELEASE_VERSION }}
          key: linux-${{ env.RELEASE_VERSION }}

      - name: Cache Mac artifacts
        uses: actions/cache@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          path: ./MpChatDemoMac/MpChatDemo/${{ env.RELEASE_VERSION }}
          key: mac-${{ env.RELEASE_VERSION }}

      - name: Cache Win artifacts
        uses: actions/cache@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          path: ./MpChatDemoWin/MpChatDemo/${{ env.RELEASE_VERSION }}
          key: win-${{ env.RELEASE_VERSION }}

      - name: SSH Server Deploy Android artifacts
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
          local: './MpChatDemoAndroid/MpChatDemo'
          remote: '~/files'
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          user: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          scp_options: -vpr

      - name: SSH Server Deploy Linux artifacts
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
          local: './MpChatDemoLinux/MpChatDemo'
          remote: '~/files'
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          user: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          scp_options: -vpr

      - name: SSH Server Deploy Mac artifacts
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
          local: './MpChatDemoMac/MpChatDemo'
          remote: '~/files'
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          user: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          scp_options: -vpr

      - name: SSH Server Deploy Win artifacts
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
          local: './MpChatDemoWin/MpChatDemo'
          remote: '~/files'
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          user: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          scp_options: -vpr


  build-readme:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ steps.vars.outputs.tag }}

      - name: Build Readme
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: ./buildReadme.sh ${{ env.RELEASE_VERSION }}

      - name: Git Commit and Push README.md
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          commit_message: README.md for tag ${{ env.RELEASE_VERSION }}
          branch: master
          commit_user_name: Sascha Zieger
          commit_user_email: saschazieger@gmail.com
          commit_author: Author <saschazieger@gmail.com>


