name: MpChatDemo CI

on:
  push:
    tags:
      - 'v*.*.*'

#  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build with Gradle
        run: ./applyTag.sh ${{ steps.vars.outputs.tag }} && ./assembleApk.sh ${{secrets.ANDROID_KEY_PASSWORD}}

      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: ./MpChatDemoAndroid/MpChatDemo/${{ steps.vars.outputs.tag }}
          key: android-${{ steps.vars.outputs.tag }}

      - name: Prepare Release
        run: |
          mkdir -p ./MpChatDemoAndroid/MpChatDemo/${{ steps.vars.outputs.tag }}
          cp ./MpChatAndroidDemo.apk ./MpChatDemoAndroid/MpChatDemo/${{ steps.vars.outputs.tag }}/MpChatDemo-android-${{ steps.vars.outputs.tag }}.apk


  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build with Gradle
        run: ./applyTag.sh ${{ steps.vars.outputs.tag }} && ./gradlew packageDeb packageUberJarForCurrentOS

      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: ./MpChatDemoLinux/MpChatDemo/${{ steps.vars.outputs.tag }}
          key: linux-${{ steps.vars.outputs.tag }}

      - name: Prepare Release
        run: |
          mkdir -p ./MpChatDemoLinux/MpChatDemo/${{ steps.vars.outputs.tag }}
          cp ./desktop/build/compose/jars/*.jar ./MpChatDemoLinux/MpChatDemo/${{ steps.vars.outputs.tag }}/MpChatDemo-linux-jvm-${{ steps.vars.outputs.tag }}.jar
          cp ./desktop/build/compose/binaries/main/deb/*.deb ./MpChatDemoLinux/MpChatDemo/${{ steps.vars.outputs.tag }}/MpChatDemo-linux-native-${{ steps.vars.outputs.tag }}.deb


  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build with Gradle
        run: ./gradlew packageDmg packageUberJarForCurrentOS

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: ./MpChatDemoMac/MpChatDemo/${{ steps.vars.outputs.tag }}
          key: mac-${{ steps.vars.outputs.tag }}

      - name: Prepare Release
        run: |
          mkdir -p ./MpChatDemoMac/MpChatDemo/${{ steps.vars.outputs.tag }}
          cp ./desktop/build/compose/jars/*.jar ./MpChatDemoMac/MpChatDemo/${{ steps.vars.outputs.tag }}/MpChatDemo-mac-jvm-${{ steps.vars.outputs.tag }}.jar
          cp ./desktop/build/compose/binaries/main/dmg/*.dmg ./MpChatDemoMac/MpChatDemo/${{ steps.vars.outputs.tag }}/MpChatDemo-mac-native-${{ steps.vars.outputs.tag }}.dmg


  build-win:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v2
  
       - uses: actions/setup-java@v1
         with:
           java-version: 15
  
       - name: Get latest release version number
         id: get_version
         uses: battila7/get-version-action@v2
  
       - name: Build with Gradle
         run: .\gradlew.bat packageMsi packageUberJarForCurrentOS
         
       - name: Prepare Release
         run: |
           mkdir .\MpChatDemoWin\MpChatDemo\${{ steps.get_version.outputs.version }}
           copy .\desktop\build\compose\jars\*.jar .\MpChatDemoWin\MpChatDemo\${{ steps.get_version.outputs.version }}\MpChatDemo-windows-jvm-${{ steps.get_version.outputs.version }}.jar
           copy .\desktop\build\compose\binaries\main\msi\*.msi .\MpChatDemoWin\MpChatDemo\${{ steps.get_version.outputs.version }}\MpChatDemo-windows-native-${{ steps.get_version.outputs.version }}.msi
                 
       - name: Upload win artifacts
         uses: actions/upload-artifact@v2
         with:
           name: windows${{ steps.get_version.outputs.version }}
           path: .\MpChatDemoWin\MpChatDemo\${{ steps.get_version.outputs.version }}
           retention-days: 1


  trigger-webserver:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger WebServer to build new version
        uses: appleboy/ssh-action@master
        with:
          script: cd ./docker/KotlinMpChatDemo && git pull && ./rebuild.sh && ./restart.sh
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
      

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-android, build-linux, build-mac, build-win ]
    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ steps.vars.outputs.tag }}        

      - name: Cache Android artifact
        uses: actions/cache@v2
        with:
          path: ./MpChatDemoAndroid/MpChatDemo/${{ steps.vars.outputs.tag }}
          key: android-${{ steps.vars.outputs.tag }}

      - name: Cache Linux artifacts
        uses: actions/cache@v2
        with:
          path: ./MpChatDemoLinux/MpChatDemo/${{ steps.vars.outputs.tag }}
          key: linux-${{ steps.vars.outputs.tag }}

      - name: Cache Mac artifacts
        uses: actions/cache@v2
        with:
          path: ./MpChatDemoMac/MpChatDemo/${{ steps.vars.outputs.tag }}
          key: mac-${{ steps.vars.outputs.tag }}
      
      - name: Download win artifacts  
        uses: actions/download-artifact@v2
        with:
          name: windows${{  steps.vars.outputs.tag }}
          path: ./MpChatDemoWin/MpChatDemo/${{  steps.vars.outputs.tag }}

      - name: SSH Server Deploy Android artifacts
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
          local: './MpChatDemoAndroid/MpChatDemo'
          remote: '~/files'
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          user: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          scp_options: -vpr

      - name: SSH Server Deploy Linux artifacts
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
          local: './MpChatDemoLinux/MpChatDemo'
          remote: '~/files'
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          user: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          scp_options: -vpr

      - name: SSH Server Deploy Mac artifacts
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
          local: './MpChatDemoMac/MpChatDemo'
          remote: '~/files'
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          user: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          scp_options: -vpr

      - name: SSH Server Deploy Win artifacts
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
           local: './MpChatDemoWin/MpChatDemo'
           remote: '~/files'
           host: ${{secrets.SSH_HOST}}
           port: ${{secrets.SSH_PORT}}
           user: ${{secrets.SSH_USER}}
           key: ${{secrets.SSH_KEY}}
           scp_options: -vpr


  build-readme:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ steps.vars.outputs.tag }}

      - name: Build Readme
        run: ./buildReadme.sh ${{ steps.vars.outputs.tag }}

      - name: Git Commit and Push README.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: README.md for tag ${{ steps.vars.outputs.tag }}
          branch: master
          commit_user_name: Sascha Zieger
          commit_user_email: saschazieger@gmail.com
          commit_author: Author <saschazieger@gmail.com>


