name: KbmHelper CI

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Prepare Cache artifacts
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "::add-path::C:\msys64\usr\bin"

      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: .\\fooboo
          key: win-fooboo3

      - name: Prepare Release
        run: |
          mkdir .\\fooboo
          echo "boofoo" > .\\fooboo\\test.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-win ]
    steps:
      - name: Cache Win artifacts
        uses: actions/cache@v2
        with:
          path: ./fooboo
          key: win-fooboo3

      - name: test cache
        run: cat ./fooboo/test.txt
