name: KbmHelper CI

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Cache artifacts
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      . uses: actions/cache@v2
        with:
          path: ./fooboo
          key: win-fooboo

        - name: Prepare Release
          run: |
            mkdir .\\fooboo
            echo "boofoo" > .\\fooboo\\test.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-win ]
    steps:
      - name: Cache Win artifacts
        uses: actions/cache@v2
        with:
          path: ./fooboo
          key: win-fooboo

      - name: test cache
        run: cat ./fooboo/test.txt
