name: KbmHelper CI

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: ./KbmHelperWin/KbmHelper/fooboo
          key: win-fooboo

      - name: Prepare Release
        run: |
          mkdir .\\KbmHelperWin\\fooboo
          echo "fooboo" > .\\KbmHelperWin\\fooboo\\test.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-win ]
    steps:
      - name: Cache Win artifacts
        uses: actions/cache@v2
        with:
          path: ./KbmHelperWin/KbmHelper/fooboo
          key: win-fooboo

      - name: test cache
        run: cat ./KbmHelperWin/fooboo/test.txt
